# Generated by Django 2.0.5 on 2018-05-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favicon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('fav_url', models.CharField(max_length=200)),
                ('created', models.DateTimeField(verbose_name='created on')),
            ],
        ),
    ]
