# Generated by Django 2.0.5 on 2018-05-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faviconfinder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favicon',
            name='created',
            field=models.DateTimeField(editable=False, verbose_name='created on'),
        ),
        migrations.AlterField(
            model_name='favicon',
            name='fav_url',
            field=models.URLField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='favicon',
            name='url',
            field=models.URLField(),
        ),
    ]
